### ISSUE TITLE
Spielende

### ISSUE THREAD

**Issue by Keksbendiger** [WS22-Robotik-4-Gewinnt/Hardwaresteuerung#1]
Wir brauchen eine Möglichkeit, den Menschen zu signalisieren, dass das Spiel vorbei ist
im besten Fall in den 3 Unterscheidungen (LEDs oder so?)
- Sieg Spieler
- Sieg KI
- Unentschieden

Von der Algo-Seite würden wir die entsprechende Info auf einen zweiten Endpunkt senden.

**Comment by freed40** [comment]
Klingt gut
